name: tiny_regex
version: 0.3.1
description: p2p lib
autohr: kyorohiro
environment:
  sdk: '<=2.0.0'
  xml: any
dependencies:
  args: 1.0.2
  tiny_parser:
    git:
      url: https://github.com/kyorohiro/dart.tiny_parser.git
      ref: v0.0.2
dev_dependencies:
  test: any
